// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SkitseleniumtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void skitseleniumtest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("from")).click();
    {
      WebElement dropdown = driver.findElement(By.id("from"));
      dropdown.findElement(By.xpath("//option[. = 'John F. Kennedy - New York']")).click();
    }
    driver.findElement(By.id("to")).click();
    {
      WebElement dropdown = driver.findElement(By.id("to"));
      dropdown.findElement(By.xpath("//option[. = 'Miami International Airport']")).click();
    }
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("letOption")).click();
    driver.findElement(By.id("submitLet")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Ana");
    driver.findElement(By.id("surename")).click();
    driver.findElement(By.id("surename")).sendKeys("Georgieska");
    driver.findElement(By.id("passportNumber")).click();
    driver.findElement(By.id("passportNumber")).sendKeys("MK99887");
    driver.findElement(By.id("passportNumber")).click();
    driver.findElement(By.id("passportNumber")).sendKeys("MK99882");
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("seat")).click();
    {
      WebElement dropdown = driver.findElement(By.id("seat"));
      dropdown.findElement(By.xpath("//option[. = '4']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
}
